
## Elasticsearch ##
## set node_name ##
#node_name: "{{ inventory_hostname }}"

## set CA cert path, SSL cert path and SSL key path ##

#es_ca_path: "{{ es_cert_dir }}/ca/ca.crt"

## hot ##
#es_ssl_cert_path_hot: "{{ es_cert_dir }}/hot/hot.crt"
#es_ssl_key_path_hot: "{{ es_cert_dir }}/hot/hot.key"

## warm ##
#es_ssl_cert_path_warm: "{{ es_cert_dir }}/warm/warm.crt"
#es_ssl_key_path_warm: "{{ es_cert_dir }}/warm/warm.key"

## master ##
#es_ssl_cert_path_master: "{{ es_cert_dir }}/master/master.crt"
#es_ssl_key_path_master: "{{ es_cert_dir }}/master/master.key"

## coordinating ##
#es_ssl_cert_path_coordinating: "{{ es_cert_dir }}/coordinating/coordinating.crt"
#es_ssl_key_path_coordinating: "{{ es_cert_dir }}/coordinating/coordinating.key"


## Kibana ##
## set server_name ##
#server_name: "{{ ansible_hostname }}"

## set CA cert path, SSL cert path and SSL key path ##
#kb_ca_path: "{{ kb_cert_dir }}/ca/ca.crt"
#kb_ssl_cert_path: "{{ kb_cert_dir }}/kb/kb.crt"
#kb_ssl_key_path: "{{ kb_cert_dir }}/kb/kb.key"


## Metricbeat ##
## change metricbeat output location ##
#mb_output_elasticsearch: "https://es-test:9200"
